version: '3.6'
services:
  mongo1:
    image: "mongo:4.0-xenial"
    container_name: mongo1
    command: --replSet rs0 --smallfiles --oplogSize 128
    volumes:
      - rs1:/data/db
    networks:
      - localnet2
    ports:
      - "27017:27017"
    restart: always
  mongo2:
    image: "mongo:4.0-xenial"
    container_name: mongo2
    command: --replSet rs0 --smallfiles --oplogSize 128
    volumes:
      - rs2:/data/db
    networks:
      - localnet2
    ports:
      - "27018:27017"
    restart: always
  mongo3:
    image: "mongo:4.0-xenial"
    container_name: mongo3
    command: --replSet rs0 --smallfiles --oplogSize 128
    volumes:
      - rs3:/data/db
    networks:
      - localnet2
    ports:
      - "27019:27017"
    restart: always

  stockgenmongo:
   image: "stockgenmongo:0.1"
   hostname: stockgenmongotest
   container_name: stockgenmongotest
   networks:
     - localnet2

  stockportal:
   image: "stockportal:0.1"
   hostname: stockportal
   container_name: stockportal
   networks:
     - localnet2
   depends_on:
     - mongo1
   ports:
     - 8088:80



networks:
  localnet2:
    attachable: true

volumes:
  rs1:
  rs2:
  rs3:
